name: Build
on: [push]
jobs:
  Build-QtChess:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: '6.3.0'
      - name: CMake
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
      - run: echo "Build Status ${{ job.status }}."
