name: Check-Format

on: push

jobs:
  Check-Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: clang-format Check
        uses: jidicula/clang-format-action@v4.8.0
        with:
          clang-format-version: 14
          fallback-style: 'Google'